#:schema https://docs.jj-vcs.dev/latest/config-schema.json

[user]
name = "Julian"
email = "julianorlich1@gmail.com"

[ui]
color = "auto"
editor = "nvim"

[aliases]
move = ["bookmark", "move", "--to", "@-"]
push = ["git", "push", "--bookmark"]
