set -g @status-bg "#{?#{E:@current-window-in-mode},#0074b1,#{?client_prefix,#008800,#009393}}"
set -g @window-status-bg "#{?#{E:@current-window-in-mode},#005f8f,#{?client_prefix,#2A6500,#007f7f}}"
set -g @window-status-current-bg "#{?#{E:@current-window-in-mode},#003f63,#{?client_prefix,#004f00,#004f4f}}"
set -g cursor-colour "#009393"
set -g @copy-mode-cursor "#0074b1"
set -g status-style "bg=#{E:@status-bg},fg=#ffffff,fill=#{E:@status-bg}"
set -g status-left-style "bg=#{E:@status-bg},fg=#ffffff,fill=#{E:@status-bg}"
set -g status-right-style "bg=#{E:@status-bg},fg=#ffffff,fill=#{E:@status-bg}"
set -g message-style "bg=#008800,fg=#ffffff"
set -g message-command-style "bg=#008800,fg=#ffffff"
set -g prompt-cursor-colour "#ffffff"
setw -g mode-style "bg=#C4FFFF,fg=#000000"
set -g window-status-current-style "bg=#{E:@window-status-current-bg},fg=#ffffff"
set -g window-status-style "bg=#{E:@window-status-bg},fg=#cccccc"
