set -g @status-bg "#{?#{E:@current-window-in-mode},#7aa2f7,#{?client_prefix,#8bd49c,#5bc8af}}"
set -g @window-status-bg "#{?#{E:@current-window-in-mode},#506b9f,#{?client_prefix,#657a55,#397f73}}"
set -g @window-status-current-bg "#{?#{E:@current-window-in-mode},#3b527d,#{?client_prefix,#40553f,#285e56}}"
set -g cursor-colour "#5bc8af"
set -g @copy-mode-cursor "#7aa2f7"
set -g status-style "bg=#{E:@status-bg},fg=#202026,fill=#{E:@status-bg}"
set -g status-left-style "bg=#{E:@status-bg},fg=#202026,fill=#{E:@status-bg}"
set -g status-right-style "bg=#{E:@status-bg},fg=#202026,fill=#{E:@status-bg}"
set -g message-style "bg=#8bd49c,fg=#202026"
set -g message-command-style "bg=#8bd49c,fg=#202026"
set -g prompt-cursor-colour "#202026"
setw -g mode-style "bg=#34495e,fg=#f2f2f4"
set -g window-status-current-style "bg=#{E:@window-status-current-bg},fg=#f2f2f4"
set -g window-status-style "bg=#{E:@window-status-bg},fg=#d8d8dc"
