[bluetooth]
device_mac = "9C:0D:AC:14:8D:42"

[calendar_popup]
width = 248
right_inset = 5
top_offset = -1

[icons]
dark = "#303030"
light = "#ffffff"

[icons.overrides]
"steam" = "assets/icons/steam-mono.svg"
"steam_app_2225070" = "assets/icons/trackmania-mono.svg"
"kitty" = "assets/icons/terminal-mono.svg"
"zen" = "assets/icons/zen-mono.svg"
