#include ~/.cache/wal/colors-kitty.conf
background_opacity 1.00
dynamic_background_opacity yes
font_family IosevkaTermSlab Nerd Font Mono
font_size 20
clipboard_control write-clipboard write-primary read-clipboard read-primary
confirm_os_window_close 0
hide_window_decorations titlebar-only
enable_audio_bell no

macos_option_as_alt left

text_composition_strategy legacy

cursor_trail 1
cursor_trail_decay 0.01 0.5

background                #fcf9f0
foreground                #000000

#selection_background      #303030
#selection_foreground      #c0bfbc
#
#url_color                 #1a5fb4
#
#wayland_titlebar_color    #1B1714
#macos_titlebar_color      system
#
cursor                     #009393
cursor_text_color          #FFFFFF
#
#active_border_color       #4f4f4f
#inactive_border_color     #282828
#bell_border_color         #ed333b
#visual_bell_color         none
#
#active_tab_background     #242424
#active_tab_foreground     #fcfcfc
#inactive_tab_background   #303030
#inactive_tab_foreground   #b0afac
#tab_bar_background        none
#tab_bar_margin_color      none
#
#color0                    #1d1d1d
#color1                    #ed333b
#color2                    #57e389
#color3                    #ff7800
color4                     #009504
#color5                    #CDCA2E
#color6                    #5bc8af
#color7                    #deddda
#
#color8                    #9a9996
#color9                    #f66151
#color10                   #8ff0a4
#color11                   #ffa348
color12                    #71BD59
#color13                   #dc8add
#color14                   #93ddc2
#color15                   #f6f5f4


# BEGIN_KITTY_FONTS
#font_family      family='JetBrainsMono Nerd Font Mono' postscript_name=JetBrainsMonoNFM-Regular
#bold_font        family='JetBrainsMono Nerd Font Mono' postscript_name=JetBrainsMonoNFM-ExtraBold
#italic_font      family='JetBrainsMono Nerd Font Mono' style='SemiBold Italic'
#bold_italic_font family='JetBrainsMono Nerd Font Mono' postscript_name=JetBrainsMonoNFM-ExtraBoldItalic
# END_KITTY_FONTS
