background #@background@
foreground #@foreground@
cursor #@secondary@
cursor_text_color #@terminalCursorText@
selection_background #@selection@
selection_foreground #@selectionForeground@
url_color #@accent@
color0 #@ansiBlack@
color1 #@danger@
color2 #@success@
color3 #@warning@
color4 #@ansiBlue@
color5 #@purple@
color6 #@secondary@
color7 #@terminalWhite@
color8 #@muted@
color9 #@dangerBright@
color10 #@successBright@
color11 #@warningBright@
color12 #@accentBright@
color13 #@purpleBright@
color14 #@secondaryBright@
color15 #@bright@
