background #@background@
foreground #@foreground@
cursor #@secondary@
cursor_text_color #@background@
selection_background #@selection@
selection_foreground #@foreground@
url_color #@accent@
color0 #@background@
color1 #@danger@
color2 #@success@
color3 #@warning@
color4 #@accent@
color5 #@purple@
color6 #@secondary@
color7 #@terminalWhite@
color8 #@muted@
color9 #@danger@
color10 #@success@
color11 #@warning@
color12 #@accent@
color13 #@purple@
color14 #@secondary@
color15 #@bright@
