color=@backgroundBare@
inside-color=@backgroundBare@
ring-color=@secondaryBare@
line-color=@backgroundBare@
text-color=@foregroundBare@
key-hl-color=@successBare@
bs-hl-color=@dangerBare@
separator-color=@backgroundBare@
