set -g @status-bg "#{?#{E:@current-window-in-mode},#@accent@,#{?client_prefix,#@success@,#@secondary@}}"
set -g @window-status-bg "#{?#{E:@current-window-in-mode},#@tmuxWindowMode@,#{?client_prefix,#@tmuxWindowPrefix@,#@tmuxWindowNormal@}}"
set -g @window-status-current-bg "#{?#{E:@current-window-in-mode},#@accentStrong@,#{?client_prefix,#@successStrong@,#@tmuxSecondaryCurrent@}}"
set -g cursor-colour "#@secondary@"
set -g @copy-mode-cursor "#@accent@"
set -g status-style "bg=#{E:@status-bg},fg=#@tmuxForeground@,fill=#{E:@status-bg}"
set -g status-left-style "bg=#{E:@status-bg},fg=#@tmuxForeground@,fill=#{E:@status-bg}"
set -g status-right-style "bg=#{E:@status-bg},fg=#@tmuxForeground@,fill=#{E:@status-bg}"
set -g message-style "bg=#@success@,fg=#@tmuxForeground@"
set -g message-command-style "bg=#@success@,fg=#@tmuxForeground@"
set -g prompt-cursor-colour "#@tmuxForeground@"
setw -g mode-style "bg=#@selection@,fg=#@foreground@"
set -g window-status-current-style "bg=#{E:@window-status-current-bg},fg=#@tmuxCurrentForeground@"
set -g window-status-style "bg=#{E:@window-status-bg},fg=#@tmuxWindowForeground@"
