set -g @status-bg "#{?#{E:@current-window-in-mode},#@accent@,#{?client_prefix,#@success@,#@secondary@}}"
set -g @window-status-bg "#{?#{E:@current-window-in-mode},#@surfaceStrong@,#{?client_prefix,#@surfaceStrong@,#@surfaceStrong@}}"
set -g @window-status-current-bg "#{?#{E:@current-window-in-mode},#@accentStrong@,#{?client_prefix,#@successStrong@,#@secondaryStrong@}}"
set -g cursor-colour "#@secondary@"
set -g @copy-mode-cursor "#@accent@"
set -g status-style "bg=#{E:@status-bg},fg=#@onColor@,fill=#{E:@status-bg}"
set -g status-left-style "bg=#{E:@status-bg},fg=#@onColor@,fill=#{E:@status-bg}"
set -g status-right-style "bg=#{E:@status-bg},fg=#@onColor@,fill=#{E:@status-bg}"
set -g message-style "bg=#@success@,fg=#@onColor@"
set -g message-command-style "bg=#@success@,fg=#@onColor@"
set -g prompt-cursor-colour "#@onColor@"
setw -g mode-style "bg=#@selection@,fg=#@foreground@"
set -g window-status-current-style "bg=#{E:@window-status-current-bg},fg=#@bright@"
set -g window-status-style "bg=#{E:@window-status-bg},fg=#@subtle@"
